### PR TITLE
feature/when-bus-arrives-set-0-instead-of-a-lapproche

### PR DESCRIPTION
**Pull request by wgrs33**
Show blinking 0 when bus arrives, if no next bus, show empty gray place - set fixed size

### CODE REVIEW

**Comment by yyrkoon94** [comment]
Hi @wgrs33,

Thanks for this PR. I not totally agree with the change : I like to have "à l'approche" and "à l'arrêt" on my wall panel. So probably we can add this change as an option (display_stop_label:true/false) so we can add the 2 possibilities (and by default "true" because it's the case today)

What do you think ?

**Comment by wgrs33** [comment]
Hi @yyrkoon94,

Ha, I pushed this PR because my observations are different! By default all bus screens don't display the text, only `0`. I checked it randomly on Pont de Sevres and Gare de Lyon. That's why I would say that this option should be `false` by default, but it's your decision ;)

**Comment by yyrkoon94** [comment]
Oh you're talking about "real screens" :D Yes, I did the same behavior for RER and BUS but I agree that the real displays for buses are a little different. It's been a while since I checked the display in the bus station so if you think it's better to display "0" (flashing when the bus arrives) go for it ;)

**Comment by wgrs33** [comment]
Ok, I'll add the option to the config, but only for the BUS type, right? Do we want to have it also in the TRAIN type screen?

**Comment by yyrkoon94** [comment]
Hello, no only for BUS type.

**Comment by wgrs33** [comment]
I added the option to the configuration card. The switch will only be enabled if the user chooses BUS type. Works fine.
I'm not sure if the position of this switch is ok but I placed it next to the other switches. Let me know if it should be place elsewhere.

**Pull request merged**
